### ISSUE TITLE
command "ntc" returns error

### ISSUE THREAD

**Issue by keevvinc** [ryanzec/name-that-color#4]
Hello,

when I use **ntc** it returns 
> env: node\r: No such file or directory

Is there any way I can solve this?

Im running mac Os Sierra.
Thanks

**Comment by ryanzec** [comment]
I just tested on Sierra and is works fine for me.

I am not sure if you are talking about another project as this one does not create a command called `ntc` is creates one called `name-that-color`

**Comment by keevvinc** [comment]
Oh, I am sorry. I don't know why I thought the command is ntc, instead of 'name-that-color'.
Problem solved, I guess You can close this issue :-) Thanks
